### ISSUE TITLE
estimating coverage error

### ISSUE THREAD

**Issue by bishopia** [tomh1lll/dudeml#2]
trying out the test case in the README file, any thoughts on why I'm getting these errors with winstat? everything installed just fine. EDIT: followed advice in #1 and made a fake chr file, seems to have worked

```
(dudeml3)[user@login006 dudeml]$ for i in train test
> do
> python3 dudeML.py simReads -fasta DiNV_CH01M.fa -cov 20 -d ${i}_sim -id ${i} -RL 100
> bwa mem -t 4 DiNV_CH01M.fa.masked ${i}_sim/${i}_20_1.fq ${i}_sim/${i}_20_2.fq | samtools view -Shb - | samtools sort - > ${i}_sim/total.bam
> python3 dudeML.py winStat -i${i}_sim/total.bam -o ${i}_sim/total_50.bed -w 50 -s 50
> done
[wgsim] seed = 1669754299
[wgsim_core] calculating the total length of the reference sequence...
[wgsim_core] 1 sequences, total length: 170123
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 31120 sequences (3112000 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 14197, 672, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (459, 495, 530)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (317, 672)
[M::mem_pestat] mean and std.dev: (493.53, 51.82)
[M::mem_pestat] low and high boundaries for proper pairs: (246, 743)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (422, 848, 921)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1919)
[M::mem_pestat] mean and std.dev: (687.06, 259.30)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2418)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 31120 reads in 1.497 CPU sec, 0.377 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 DiNV_CH01M.fa.masked train_sim/train_20_1.fq train_sim/train_20_2.fq
[main] Real time: 0.695 sec; CPU: 1.536 sec
Calculating median coverage
Traceback (most recent call last):
  File "dudeML.py", line 292, in <module>
    for line in open(args.CHROMOSOME):
TypeError: expected str, bytes or os.PathLike object, not NoneType
[wgsim] seed = 1669754302
[wgsim_core] calculating the total length of the reference sequence...
[wgsim_core] 1 sequences, total length: 171643
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 31120 sequences (3112000 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 13944, 941, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (459, 495, 530)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (317, 672)
[M::mem_pestat] mean and std.dev: (493.44, 52.39)
[M::mem_pestat] low and high boundaries for proper pairs: (246, 743)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (94, 324, 817)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2263)
[M::mem_pestat] mean and std.dev: (402.32, 329.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2986)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 31120 reads in 3.153 CPU sec, 0.791 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 DiNV_CH01M.fa.masked test_sim/test_20_1.fq test_sim/test_20_2.fq
[main] Real time: 1.107 sec; CPU: 3.193 sec
Calculating median coverage
Traceback (most recent call last):
  File "dudeML.py", line 292, in <module>
    for line in open(args.CHROMOSOME):
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by watogo97** [comment]
Hi, I got same error. How did you solve this?
